### ISSUE TITLE
NLZIET issue

### ISSUE THREAD

**Issue by joydashy** [deviant-aut/HA-androidtv11#2]
Installed this addon to improve the Shield experience.

However, when I open (or play from) the NLZIET app, my Shield entity in HA will go to "unavailable". Is that working as intended?

**Comment by deviant-aut** [comment]
I dont have an account for NLZIET. The login screen shows me the state "paused".  Do other apps work correctly?

Did you have a look on "state_detection_rules". I use this on some apps.

**Comment by deviant-aut** [comment]
pretty hard to reproduce for me but looks like there is an issue with the state detection.

Please remove the built in state detection and let me know if it works for you.

[remove state detection](https://github.com/deviant-aut/HA-androidtv11/pull/5/commits/b9712b5cd78760123680f6f250380e992217fc3e)

**Comment by joydashy** [comment]
This seems to work!

**Comment by deviant-aut** [comment]
#5 removed nlziet state detectiob
